name: opthalmology
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  colornames: ^0.1.0
  copy_with_extension: ^5.0.4
  dart_frog: ^1.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  hive: ^4.0.0-dev.2 
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  states_rebuilder: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.7
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
