name: opthalmology
description: An EYE -> opthalmicMCQ project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  colornames: ^0.1.0
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.6
  dart_frog: ^1.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  path_provider: ^2.1.1
  states_rebuilder: ^6.3.0
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
flutter:
  uses-material-design: true
